const fenixCoursePageUrlTemplate = 'https://fenix.tecnico.ulisboa.pt/disciplinas/{fenixAcronym}/2026-2027/{semester}-semestre';

const courseMetadataByAcronym = {
    ALC: {
        acronym: 'ALC',
        name: 'Algoritmos para Lógica Computacional',
        semester: 1,
        period: 'P1',
        execution: 'ALC',
        limit: 48,
        limitLabel: '48',
        fenixAcronym: 'ALC112',
    },
    CRC: {
        acronym: 'CRC',
        name: 'Ciência de Redes Complexas',
        semester: 1,
        period: 'P1',
        execution: 'CRC',
        limit: 130,
        limitLabel: '130',
        fenixAcronym: 'ARC112',
    },
    CC: {
        acronym: 'CC',
        name: 'Computabilidade e Complexidade',
        semester: 1,
        period: 'Sem',
        execution: 'CC',
        limit: null,
        limitLabel: 'no limit',
        fenixAcronym: 'CC112',
    },
    AA: {
        acronym: 'AA',
        name: 'Algoritmos Avançados',
        semester: 2,
        period: 'P3',
        execution: 'AA',
        limit: 58,
        limitLabel: '58',
        fenixAcronym: 'AAva3610',
    },
    CPD: {
        acronym: 'CPD',
        name: 'Computação Paralela e Distribuída',
        semester: 2,
        period: 'P3',
        execution: 'CPD',
        limit: 144,
        limitLabel: '144',
        fenixAcronym: 'CPD23610',
    },
    LProg: {
        acronym: 'LProg',
        name: 'Linguagens de Programação',
        semester: 2,
        period: 'P4',
        execution: 'LProg',
        limit: 60,
        limitLabel: '60',
        fenixAcronym: 'LPro3610',
    },
    AProf: {
        acronym: 'AProf',
        name: 'Aprendizagem Profunda (Dei)',
        semester: 1,
        period: 'P2',
        execution: 'AProf',
        limit: 210,
        limitLabel: '210',
        fenixAcronym: 'AP112',
    },
    BC: {
        acronym: 'BC',
        name: 'Biologia Computacional',
        semester: 1,
        period: 'P1',
        execution: 'BC',
        limit: null,
        limitLabel: 'no limit',
        fenixAcronym: 'BC2112',
    },
    TIDB: {
        acronym: 'TIDB',
        name: 'Tecnologias de Informação e Decisão Biomédica',
        semester: 2,
        period: 'P3',
        execution: 'TIDB',
        limit: 90,
        limitLabel: '90',
        fenixAcronym: 'TIS3610',
    },
    CSF: {
        acronym: 'CSF',
        name: 'Ciber Segurança Forense',
        semester: 1,
        period: 'P1',
        execution: 'CSF',
        limit: 216,
        limitLabel: '216',
        fenixAcronym: 'CSF2112',
    },
    SegSof: {
        acronym: 'SegSof',
        name: 'Segurança em Software',
        semester: 1,
        period: 'P2',
        execution: 'AS',
        limit: 90,
        limitLabel: '90',
        fenixAcronym: 'ASof112',
    },
    SIRS: {
        acronym: 'SIRS',
        name: 'Segurança Informática em Redes e Sistemas',
        semester: 1,
        period: 'P2',
        execution: 'SIRS',
        limit: 211,
        limitLabel: '211',
        fenixAcronym: 'SIRS112',
    },
    CPS: {
        acronym: 'CPS',
        name: 'Criptografia e Protocolos de Segurança',
        semester: 2,
        period: 'Sem',
        execution: 'CPS',
        limit: null,
        limitLabel: 'no limit',
        fenixAcronym: 'CPS3610',
    },
    SGSI: {
        acronym: 'SGSI',
        name: 'Segurança e Gestão de Sistemas de Informação',
        semester: 2,
        period: 'P4',
        execution: 'SGSI',
        limit: null,
        limitLabel: 'no limit',
        fenixAcronym: 'OGFI3610',
    },
    SEC: {
        acronym: 'SEC',
        name: 'Sistemas de Elevada Confiabilidade',
        semester: 2,
        period: 'P3',
        execution: 'SEC',
        limit: 160,
        limitLabel: '160',
        fenixAcronym: 'SDTF23610',
    },
    AS: {
        acronym: 'AS',
        name: 'Arquitectura de Software',
        semester: 1,
        period: 'P2',
        execution: 'AS',
        limit: 90,
        limitLabel: '90',
        fenixAcronym: 'ASof112',
    },
    AES: {
        acronym: 'AES',
        name: 'Análise e Especificação de Software',
        semester: 1,
        period: 'P2',
        execution: 'AES',
        limit: null,
        limitLabel: 'n/a',
        fenixAcronym: null,
    },
    GPI: {
        acronym: 'GPI',
        name: 'Gestão de Projectos Informáticos',
        semester: 2,
        period: 'P3',
        execution: 'GPI',
        limit: 96,
        limitLabel: '96',
        fenixAcronym: 'GPI3610',
    },
    PA: {
        acronym: 'PA',
        name: 'Programação Avançada',
        semester: 1,
        period: 'P1',
        execution: 'PA',
        limit: null,
        limitLabel: 'n/a',
        fenixAcronym: null,
    },
    TVS: {
        acronym: 'TVS',
        name: 'Teste e Validação de Software',
        semester: 2,
        period: 'P4',
        execution: 'TVS',
        limit: 84,
        limitLabel: '84',
        fenixAcronym: 'TVS3610',
    },
    AID: {
        acronym: 'AID',
        name: 'Análise e Integração de Dados',
        semester: 1,
        period: 'P1',
        execution: 'AID',
        limit: 140,
        limitLabel: '140',
        fenixAcronym: 'GTI112',
    },
    CD: {
        acronym: 'CD',
        name: 'Ciência de Dados',
        semester: 1,
        period: 'P2',
        execution: 'CD',
        limit: 216,
        limitLabel: '216',
        fenixAcronym: 'CDadosi2112',
    },
    VI: {
        acronym: 'VI',
        name: 'Visualização de Informação',
        semester: 1,
        period: 'P1',
        execution: 'VI',
        limit: 133,
        limitLabel: '133',
        fenixAcronym: 'VI222',
    },
    AIP: {
        acronym: 'AIP',
        name: 'Análise Inteligente de Processos',
        semester: 1,
        period: 'P2',
        execution: 'AIP',
        limit: null,
        limitLabel: 'n/a',
        fenixAcronym: null,
    },
    SIP: {
        acronym: 'SIP',
        name: 'Sistemas Inteligentes de Pesquisa',
        semester: 1,
        period: 'P2',
        execution: 'SIP',
        limit: null,
        limitLabel: 'n/a',
        fenixAcronym: null,
    },
    PSI: {
        acronym: 'PSI',
        name: 'Plataformas de Suporte a Ia',
        semester: 2,
        period: 'P4',
        execution: 'PSI',
        limit: null,
        limitLabel: 'n/a',
        fenixAcronym: null,
    },
    DDRS: {
        acronym: 'DDRS',
        name: 'Desempenho e Dimensionamento de Redes e Sistemas',
        semester: 1,
        period: 'P2',
        execution: 'DDRS',
        limit: null,
        limitLabel: 'no execution 25/26',
        fenixAcronym: 'DDRS',
    },
    ESAD: {
        acronym: 'ESAD',
        name: 'Engenharia de Sistemas de Alto Desempenho',
        semester: 2,
        period: 'P4',
        execution: 'ESAD',
        limit: null,
        limitLabel: 'n/a',
        fenixAcronym: null,
    },
    ADSI: {
        acronym: 'ADSI',
        name: 'Administração de Dados e Sistemas de Informação',
        semester: 2,
        period: 'P3',
        execution: 'ADSI',
        limit: 110,
        limitLabel: '110',
        fenixAcronym: 'AOBD3610',
    },
    CNV: {
        acronym: 'CNV',
        name: 'Computação em Nuvem e Virtualização',
        semester: 2,
        period: 'P4',
        execution: 'CNV',
        limit: 145,
        limitLabel: '145',
        fenixAcronym: 'AVExe23610',
    },
    IAES: {
        acronym: 'IAES',
        name: 'Inteligência Artificial Explicável Simbólica',
        semester: 1,
        period: 'P2',
        execution: 'IAES',
        limit: null,
        limitLabel: 'n/a',
        fenixAcronym: null,
    },
    LN: {
        acronym: 'LN',
        name: 'Língua Natural',
        semester: 1,
        period: 'P1',
        execution: 'LN',
        limit: 223,
        limitLabel: '223',
        fenixAcronym: 'LN2112',
    },
    IP: {
        acronym: 'IP',
        name: 'Interação Pessoa-Ia',
        semester: 1,
        period: 'P2',
        execution: 'IP',
        limit: null,
        limitLabel: 'n/a',
        fenixAcronym: null,
    },
    PADI: {
        acronym: 'PADI',
        name: 'Planeamento, Aprendizagem e Decisão Inteligente',
        semester: 1,
        period: 'P1',
        execution: 'DAD',
        limit: 130,
        limitLabel: '130',
        fenixAcronym: 'PADI112',
    },
    AVTM: {
        acronym: 'AVTM',
        name: 'Animação e Visualização Tridimensional Móvel',
        semester: 1,
        period: 'P1',
        execution: 'AVT',
        limit: 48,
        limitLabel: '48',
        fenixAcronym: 'AVT112',
    },
    CCU: {
        acronym: 'CCU',
        name: 'Conceção Centrada no Utilizador',
        semester: 1,
        period: 'P2',
        execution: 'CCU',
        limit: 180,
        limitLabel: '180',
        fenixAcronym: 'CCU112',
    },
    DIRVAM: {
        acronym: 'DIRVAM',
        name: 'Design de Interação para Realidade Virtual, Aumentada e Mista',
        semester: 1,
        period: 'P2',
        execution: 'DIRVAM',
        limit: null,
        limitLabel: 'n/a',
        fenixAcronym: null,
    },
    CV: {
        acronym: 'CV',
        name: 'Computação Visual',
        semester: 2,
        period: 'P3',
        execution: 'CV',
        limit: 60,
        limitLabel: '60',
        fenixAcronym: 'CVI10',
    },
    PCM: {
        acronym: 'PCM',
        name: 'Produção de Conteúdos Multimédia',
        semester: 2,
        period: 'P3',
        execution: 'PCM',
        limit: 104,
        limitLabel: '104',
        fenixAcronym: 'PCM3610',
    },
    P: {
        acronym: 'P',
        name: 'Programação 3D',
        semester: 1,
        period: 'P2',
        execution: 'P',
        limit: null,
        limitLabel: 'n/a',
        fenixAcronym: null,
    },
    CGJ: {
        acronym: 'CGJ',
        name: 'Computação Gráfica para Jogos',
        semester: 1,
        period: 'P2',
        execution: 'CGJ',
        limit: 72,
        limitLabel: '72',
        fenixAcronym: 'CGJ112',
    },
    DJ: {
        acronym: 'DJ',
        name: 'Design de Jogos',
        semester: 1,
        period: 'P1',
        execution: 'DJ',
        limit: 72,
        limitLabel: '72',
        fenixAcronym: 'DDJ112',
    },
    IAJ: {
        acronym: 'IAJ',
        name: 'Inteligência Artificial para Jogos',
        semester: 1,
        period: 'P1',
        execution: 'IAJ',
        limit: null,
        limitLabel: 'no execution 25/26',
        fenixAcronym: 'IAJ112',
    },
    MDJ: {
        acronym: 'MDJ',
        name: 'Metodologia de Desenvolvimento de Jogos',
        semester: 2,
        period: 'P4',
        execution: 'MDJ',
        limit: 72,
        limitLabel: '72',
        fenixAcronym: 'TJS3610',
    },
    IR: {
        acronym: 'IR',
        name: 'Introdução à Robótica',
        semester: 1,
        period: 'P1',
        execution: 'IR',
        limit: null,
        limitLabel: 'no limit',
        fenixAcronym: 'IRobo112',
    },
    PIV: {
        acronym: 'PIV',
        name: 'Processamento de Imagem e Visão',
        semester: 1,
        period: 'P2',
        execution: 'PIV',
        limit: null,
        limitLabel: 'no limit',
        fenixAcronym: 'PIV3112',
    },
    RSIH: {
        acronym: 'RSIH',
        name: 'Robótica Social e Interação Humanos-Robôs',
        semester: 1,
        period: 'P2',
        execution: 'RSIHR',
        limit: 54,
        limitLabel: '54',
        fenixAcronym: 'RSIPR3',
    },
    PF: {
        acronym: 'PF',
        name: 'Processamento da Fala',
        semester: 2,
        period: 'P4',
        execution: 'PF',
        limit: null,
        limitLabel: 'no limit',
        fenixAcronym: 'PF3610',
    },
    SRM: {
        acronym: 'SRM',
        name: 'Sistemas Robóticos em Manipulação',
        semester: 2,
        period: 'P4',
        execution: 'SRM',
        limit: null,
        limitLabel: 'no limit',
        fenixAcronym: 'SRMan3610',
    },
    EDI: {
        acronym: 'EDI',
        name: 'Estúdio de Design de Interação',
        semester: 1,
        period: 'P1',
        execution: 'EDI',
        limit: 144,
        limitLabel: '144',
        fenixAcronym: 'DIIC112',
    },
    AIIC: {
        acronym: 'AIIC',
        name: 'Ambientes Inteligentes e Internet das Coisas',
        semester: 1,
        period: 'P2',
        execution: 'AIIC',
        limit: null,
        limitLabel: 'n/a',
        fenixAcronym: null,
    },
    CMU: {
        acronym: 'CMU',
        name: 'Computação Móvel e Ubíqua',
        semester: 2,
        period: 'P4',
        execution: 'CMU',
        limit: 96,
        limitLabel: '96',
        fenixAcronym: 'CMov23610',
    },
    ETPN: {
        acronym: 'ETPN',
        name: 'Engenharia e Tecnologia de Processos de Negócio',
        semester: 1,
        period: 'P2',
        execution: 'ETPN',
        limit: 120,
        limitLabel: '120',
        fenixAcronym: 'ETPN112',
    },
    IE: {
        acronym: 'IE',
        name: 'Integração Empresarial',
        semester: 2,
        period: 'P4',
        execution: 'IE',
        limit: 64,
        limitLabel: '64',
        fenixAcronym: 'SEI3610',
    },
    DAD: {
        acronym: 'DAD',
        name: 'Desenvolvimento de Aplicações Distribuídas',
        semester: 1,
        period: 'P1',
        execution: 'DAD',
        limit: 130,
        limitLabel: '130',
        fenixAcronym: 'PADI112',
    },
    AE: {
        acronym: 'AE',
        name: 'Arquitectura Empresarial',
        semester: 2,
        period: 'P3',
        execution: 'AE',
        limit: 80,
        limitLabel: '80',
        fenixAcronym: 'APFSI3610',
    },
};

const areasMEIC2026 = {
    'Algoritmos e Aplicações': ['ALC', 'CRC', 'CC', 'AA', 'CPD', 'LProg'],
    'Bioinformática e Biologia Computacional': ['AProf', 'BC', 'CRC', 'AA', 'TIDB'],
    'Ciber-Segurança': ['CSF', 'SegSof', 'SIRS', 'CPS', 'SGSI', 'SEC'],
    'Engenharia de Software': ['AS', 'AES', 'SegSof', 'GPI', 'PA', 'TVS'],
    'Ciência de Dados': ['AID', 'AProf', 'CD', 'VI', 'AIP', 'SIP'],
    'Infraestruturas para Engenharia de Dados': ['PSI', 'DDRS', 'ESAD', 'SIRS', 'ADSI', 'CNV'],
    'Inteligência Artificial': ['AProf', 'CD', 'IAES', 'LN', 'IP', 'PADI'],
    'Interação e Visualização': ['AVTM', 'CCU', 'DIRVAM', 'VI', 'CV', 'PCM', 'P'],
    Jogos: ['CGJ', 'DJ', 'IAJ', 'IP', 'MDJ', 'PCM'],
    'Robótica Inteligente': ['AProf', 'IR', 'PIV', 'RSIH', 'PADI', 'PF', 'SRM'],
    'Sistemas Ciberfísicos': ['CD', 'EDI', 'IR', 'AIIC', 'CMU', 'SEC'],
    'Sistemas de Informação': ['AID', 'ETPN', 'ADSI', 'IE', 'SIP'],
    'Sistemas Distribuídos': ['DAD', 'SIRS', 'CNV', 'CMU', 'CPD', 'SEC'],
    'Sistemas Empresariais': ['PSI', 'ETPN', 'AE', 'AIP', 'GPI', 'IE', 'SGSI'],
    'Tecnologias da Informação e Linguagem Humana': ['AProf', 'LN', 'PF', 'SIP', 'PCM'],
};
