const fenixCoursePageUrlTemplate = 'https://fenix.tecnico.ulisboa.pt/disciplinas/{fenixAcronym}/2026-2027/{semester}-semestre';

const courseMetadataByAcronym = {
    ALC: {
        name: 'Algoritmos para Lógica Computacional',
        semester: 1,
        period: 'P1',
        limit: 48,
        fenixAcronym: 'ALC',
    },
    CRC: {
        name: 'Ciência de Redes Complexas',
        semester: 1,
        period: 'P1',
        limit: 130,
        fenixAcronym: 'ARC',
    },
    CC: {
        name: 'Computabilidade e Complexidade',
        semester: 1,
        period: 'P1+P2',
        limit: null,
        fenixAcronym: 'CC',
    },
    AA: {
        name: 'Algoritmos Avançados',
        semester: 2,
        period: 'P3',
        limit: 58,
        fenixAcronym: 'AAva',
    },
    CPD: {
        name: 'Computação Paralela e Distribuída',
        semester: 2,
        period: 'P3',
        limit: 144,
        fenixAcronym: 'CPD',
    },
    LProg: {
        name: 'Linguagens de Programação',
        semester: 2,
        period: 'P4',
        limit: 60,
        fenixAcronym: 'LPro',
    },
    AProf: {
        name: 'Aprendizagem Profunda (Dei)',
        semester: 1,
        period: 'P2',
        limit: 210,
        fenixAcronym: 'AP-Dei',
    },
    BC: {
        name: 'Biologia Computacional',
        semester: 1,
        period: 'P1',
        limit: null,
        fenixAcronym: 'BC',
    },
    TIDB: {
        name: 'Tecnologias de Informação e Decisão Biomédica',
        semester: 2,
        period: 'P3',
        limit: 90,
        fenixAcronym: 'TIS',
    },
    CSF: {
        name: 'Ciber Segurança Forense',
        semester: 1,
        period: 'P1',
        limit: 216,
        fenixAcronym: 'CSF',
    },
    SegSof: {
        name: 'Segurança em Software',
        semester: 1,
        period: 'P2',
        limit: 216,
        fenixAcronym: 'ASof',
    },
    SIRS: {
        name: 'Segurança Informática em Redes e Sistemas',
        semester: 1,
        period: 'P2',
        limit: 208,
        fenixAcronym: 'SIRS',
    },
    CPS: {
        name: 'Criptografia e Protocolos de Segurança',
        semester: 2,
        period: 'P3+P4',
        limit: null,
        fenixAcronym: 'CPS',
    },
    SGSI: {
        name: 'Segurança e Gestão de Sistemas de Informação',
        semester: 2,
        period: 'P4',
        limit: null,
        fenixAcronym: 'OGFI',
    },
    SEC: {
        name: 'Sistemas de Elevada Confiabilidade',
        semester: 2,
        period: 'P3',
        limit: 160,
        fenixAcronym: 'SDTF',
    },
    AS: {
        name: 'Arquitectura de Software',
        semester: 1,
        period: 'P2',
        limit: 90,
        fenixAcronym: 'ASof',
    },
    AES: {
        name: 'Análise e Especificação de Software',
        semester: 1,
        period: 'P1',
        limit: 60,
        fenixAcronym: 'QS',
    },
    GPI: {
        name: 'Gestão de Projectos Informáticos',
        semester: 2,
        period: 'P3',
        limit: null,
        fenixAcronym: 'GPI',
    },
    PA: {
        name: 'Programação Avançada',
        semester: 2,
        period: 'P3',
        limit: 96,
        fenixAcronym: 'PAva',
    },
    TVS: {
        name: 'Teste e Validação de Software',
        semester: 2,
        period: 'P4',
        limit: 84,
        fenixAcronym: 'TVS',
    },
    AID: {
        name: 'Análise e Integração de Dados',
        semester: 1,
        period: 'P1',
        limit: 130,
        fenixAcronym: 'GTI',
    },
    CD: {
        name: 'Ciência de Dados',
        semester: 1,
        period: 'P2',
        limit: null,
        fenixAcronym: 'CDadosi',
    },
    VI: {
        name: 'Visualização de Informação',
        semester: 1,
        period: 'P1',
        limit: 133,
        fenixAcronym: 'VI',
    },
    AIP: {
        name: 'Análise Inteligente de Processos',
        semester: 2,
        period: 'P4',
        limit: null,
        fenixAcronym: 'AOSI',
    },
    SIP: {
        name: 'Sistemas Inteligentes de Pesquisa',
        semester: 2,
        period: 'P4',
        limit: 100,
        fenixAcronym: 'RGI',
    },
    PSIA: {
        name: 'Plataformas de Suporte a Ia',
        semester: 1,
        period: 'P1',
        limit: 166,
        fenixAcronym: 'AGI',
    },
    DDRS: {
        name: 'Desempenho e Dimensionamento de Redes e Sistemas',
        semester: 1,
        period: 'P1+P2',
        limit: null,
        fenixAcronym: 'DDRS',
    },
    ESAD: {
        name: 'Engenharia de Sistemas de Alto Desempenho',
        semester: 1,
        period: 'P1',
        limit: 56,
        fenixAcronym: 'ESLE',
    },
    ADSI: {
        name: 'Administração de Dados e Sistemas de Informação',
        semester: 2,
        period: 'P3',
        limit: null,
        fenixAcronym: 'AOBD',
    },
    CNV: {
        name: 'Computação em Nuvem e Virtualização',
        semester: 2,
        period: 'P4',
        limit: 145,
        fenixAcronym: 'AVExe',
    },
    IAES: {
        name: 'Inteligência Artificial Explicável Simbólica',
        semester: 1,
        period: 'P1',
        limit: 90,
        fenixAcronym: 'IAES2',
    },
    LN: {
        name: 'Língua Natural',
        semester: 1,
        period: 'P1',
        limit: 216,
        fenixAcronym: 'LN',
    },
    IPIA: {
        name: 'Interação Pessoa-IA',
        semester: 2,
        period: 'P4',
        limit: 175,
        fenixAcronym: 'AASMA',
    },
    PADInt: {
        name: 'Planeamento, Aprendizagem e Decisão Inteligente',
        semester: 2,
        period: 'P3',
        limit: 175,
        fenixAcronym: 'ADI',
    },
    AVTM: {
        name: 'Animação e Visualização Tridimensional Móvel',
        semester: 1,
        period: 'P1',
        limit: 48,
        fenixAcronym: 'AVT',
    },
    CCU: {
        name: 'Conceção Centrada no Utilizador',
        semester: 1,
        period: 'P2',
        limit: 180,
        fenixAcronym: 'CCU',
    },
    DIRVAM: {
        name: 'Design de Interação para Realidade Virtual, Aumentada e Mista',
        semester: 1,
        period: 'P2',
        limit: 72,
        fenixAcronym: 'RVir',
    },
    CV: {
        name: 'Computação Visual',
        semester: 2,
        period: 'P3',
        limit: 60,
        fenixAcronym: 'CVI',
    },
    PCM: {
        name: 'Produção de Conteúdos Multimédia',
        semester: 2,
        period: 'P3',
        limit: 104,
        fenixAcronym: 'PCM',
    },
    P3D: {
        name: 'Programação 3D',
        semester: 2,
        period: 'P4',
        limit: 48,
        fenixAcronym: 'PSJ',
    },
    CGJ: {
        name: 'Computação Gráfica para Jogos',
        semester: 1,
        period: 'P2',
        limit: 72,
        fenixAcronym: 'CGJ',
    },
    DJ: {
        name: 'Design de Jogos',
        semester: 1,
        period: 'P1',
        limit: 72,
        fenixAcronym: 'DDJ',
    },
    IAJ: {
        name: 'Inteligência Artificial para Jogos',
        semester: 1,
        period: 'P1',
        limit: 52,
        fenixAcronym: 'IAJ',
    },
    MDJ: {
        name: 'Metodologia de Desenvolvimento de Jogos',
        semester: 2,
        period: 'P3',
        limit: 72,
        fenixAcronym: 'TJS',
    },
    IR: {
        name: 'Introdução à Robótica',
        semester: 1,
        period: 'P1+P2',
        limit: null,
        fenixAcronym: 'IRobo',
    },
    PIV: {
        name: 'Processamento de Imagem e Visão',
        semester: 1,
        period: 'P1+P2',
        limit: null,
        fenixAcronym: 'PIV',
    },
    RSIHR: {
        name: 'Robótica Social e Interação Humanos-Robôs',
        semester: 1,
        period: 'P2',
        limit: 60,
        fenixAcronym: 'RSIPR',
    },
    PF: {
        name: 'Processamento da Fala',
        semester: 2,
        period: 'P3+P4',
        limit: null,
        fenixAcronym: 'PF',
    },
    SRM: {
        name: 'Sistemas Robóticos em Manipulação',
        semester: 2,
        period: 'P3+P4',
        limit: null,
        fenixAcronym: 'SRMan',
    },
    EDI: {
        name: 'Estúdio de Design de Interação',
        semester: 1,
        period: 'P1',
        limit: 144,
        fenixAcronym: 'DIIC',
    },
    AIIC: {
        name: 'Ambientes Inteligentes e Internet das Coisas',
        semester: 2,
        period: 'P3',
        limit: 54,
        fenixAcronym: 'AIIC',
    },
    CMU: {
        name: 'Computação Móvel e Ubíqua',
        semester: 2,
        period: 'P4',
        limit: 96,
        fenixAcronym: 'CMov',
    },
    ETPN: {
        name: 'Engenharia e Tecnologia de Processos de Negócio',
        semester: 1,
        period: 'P2',
        limit: null,
        fenixAcronym: 'ETPN',
    },
    IE: {
        name: 'Integração Empresarial',
        semester: 2,
        period: 'P4',
        limit: 64,
        fenixAcronym: 'SEI',
    },
    DAD: {
        name: 'Desenvolvimento de Aplicações Distribuídas',
        semester: 1,
        period: 'P1',
        limit: 130,
        fenixAcronym: 'PADI',
    },
    AE: {
        name: 'Arquitetura Empresarial',
        semester: 2,
        period: 'P3',
        limit: null,
        fenixAcronym: 'APFSI',
    },
};

const areasMEIC2026 = {
    'Algoritmos e Aplicações': ['ALC', 'CRC', 'CC', 'AA', 'CPD', 'LProg'],
    'Bioinformática e Biologia Computacional': ['AProf', 'BC', 'CRC', 'AA', 'TIDB'],
    'Ciber-Segurança': ['CSF', 'SegSof', 'SIRS', 'CPS', 'SGSI', 'SEC'],
    'Engenharia de Software': ['AS', 'AES', 'SegSof', 'GPI', 'PA', 'TVS'],
    'Ciência de Dados': ['AID', 'AProf', 'CD', 'VI', 'AIP', 'SIP'],
    'Infraestruturas para Engenharia de Dados': ['PSIA', 'DDRS', 'ESAD', 'SIRS', 'ADSI', 'CNV'],
    'Inteligência Artificial': ['AProf', 'CD', 'IAES', 'LN', 'IPIA', 'PADInt'],
    'Interação e Visualização': ['AVTM', 'CCU', 'DIRVAM', 'VI', 'CV', 'PCM', 'P3D'],
    Jogos: ['CGJ', 'DJ', 'IAJ', 'IPIA', 'MDJ', 'PCM'],
    'Robótica Inteligente': ['AProf', 'IR', 'PIV', 'RSIHR', 'PADInt', 'PF', 'SRM'],
    'Sistemas Ciberfísicos': ['CD', 'EDI', 'IR', 'AIIC', 'CMU', 'SEC'],
    'Sistemas de Informação': ['AID', 'ETPN', 'ADSI', 'IE', 'SIP'],
    'Sistemas Distribuídos': ['DAD', 'SIRS', 'CNV', 'CMU', 'CPD', 'SEC'],
    'Sistemas Empresariais': ['PSIA', 'ETPN', 'AE', 'AIP', 'GPI', 'IE', 'SGSI'],
    'Tecnologias da Informação e Linguagem Humana': ['AProf', 'LN', 'PF', 'SIP', 'PCM'],
};
